service: ec2-scheduler # NOTE: update this with your service name

frameworkVersion: "=1.41.1"

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies
  - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:StartInstances
        - ec2:StopInstances
        - ec2:RebootInstances
        - ec2:TerminateInstances
      Resource: "arn:aws:ec2:${opt:region, self:provider.region}:*:instance/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  individually: true
  exclude:
    - node_modules/**
    - README.md
    - package.json
    - package-lock.json
    - .git
    - .gitignore

functions:
  stopInstances:
    handler: src/stopInstances.handler
    description: Stop Instances with matching Tag
    events:
      - schedule:
        rate: cron(00 16 * * ? *)
        enabled: false
    memorySize: 128
    timeout: 30
  startInstances:
    handler: src/startInstances.handler
    description: Start Instances with matching Tag
    events:
      - schedule:
        rate: cron(00 05 * * ? *)
        enabled: false
    memorySize: 128
    timeout: 30
